# Generated by Django 5.2.5 on 2025-08-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('personagem', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('local_nascimento', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='imagens-cast/')),
            ],
            options={
                'verbose_name_plural': 'Atores',
            },
        ),
        migrations.CreateModel(
            name='CarrosselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='imagens-carrossel/')),
            ],
            options={
                'verbose_name_plural': 'Itens do Carrossel',
            },
        ),
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_apresentacao', models.CharField(max_length=50)),
                ('subtitulo_apresentacao', models.CharField(max_length=100)),
                ('banner', models.ImageField(upload_to='banners-elenco/')),
            ],
        ),
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_apresentacao', models.CharField(max_length=50)),
                ('subtitulo_apresentacao', models.CharField(max_length=100)),
                ('banner', models.ImageField(upload_to='banners-inicio/')),
                ('titulo_conteudo', models.CharField(max_length=50)),
                ('subtitulo_conteudo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecaoSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(blank=True, max_length=100)),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Seções do Sobre',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='logos/')),
                ('copyright', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_apresentacao', models.CharField(max_length=50)),
                ('subtitulo_apresentacao', models.CharField(max_length=100)),
                ('banner', models.ImageField(upload_to='banners-sobre/')),
                ('svg', models.FileField(null=True, upload_to='svgs/')),
            ],
        ),
    ]
