# Generated by Django 5.2.5 on 2025-08-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('personagem', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('local_nascimento', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='imagens/')),
            ],
            options={
                'verbose_name_plural': 'Atores',
            },
        ),
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_apresentacao', models.CharField(max_length=50)),
                ('subtitulo_apresentacao', models.CharField(max_length=100)),
                ('banner', models.ImageField(upload_to='banner-elenco/')),
            ],
        ),
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_apresentacao', models.CharField(max_length=50)),
                ('subtitulo_apresentacao', models.CharField(max_length=100)),
                ('banner', models.ImageField(upload_to='banner-inicio/')),
                ('titulo_conteudo', models.CharField(max_length=100)),
                ('subtitulo_conteudo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('copyright', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_apresentacao', models.CharField(max_length=50)),
                ('subtitulo_apresentacao', models.CharField(max_length=100)),
                ('banner', models.ImageField(upload_to='banner-sobre/')),
                ('titulo_conteudo', models.CharField(max_length=100)),
                ('subtitulo_conteudo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(upload_to='imagem/')),
            ],
        ),
    ]
