# Generated by Django 5.2.5 on 2025-08-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.FileField(upload_to='logo/'),
        ),
    ]
